package com.fractalwrench.bpp;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

/**
 * Executes the BPP compiler and runs the generated bytecode, and returns it output as a String
 * by redirecting Standard Out to a PrintStream.
 */
public class BppRunner {

    public static String run(String[] args) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        System.setOut(new PrintStream(baos));
        BritPlusPlus.main(args);
        byte[] bytes = baos.toByteArray();
        return new String(bytes);
    }

}
