package com.fractalwrench.britplusplus;

import java.io.File;
import java.io.FileOutputStream;

/**
 * Compiles BritPlusPlus source code to Java ByteCode.
 */
public class BritPlusPlus {

    private static final String OUTPUT_FILENAME = "Hello";

    public static void main(String[] args) throws Exception {
        String fileName = OUTPUT_FILENAME;// parseSourceFileName(args);
        String sourceCode = "test";// fetchSourceCode(fileName);

        generateByteCodeFile(sourceCode, fileName);
        DynamicClassExecutor dynamicExecutor = new DynamicClassExecutor(new File("."), fileName);
        dynamicExecutor.execute();
    }

    static String parseSourceFileName(String[] args) {
        if (args.length != 1) {
            String msg = String.format("Expected 1 argument, received %d. \n\nCorrect Usage: bpp <file>", args.length);
            throw new IllegalArgumentException(msg);
        }
        String filename = args[0];

        if (filename == null) {
            throw new IllegalArgumentException("Source file argument cannot be null!");
        }
        return filename;
    }

    static String fetchSourceCode(String fileName) {
        if (fileName == null) {
            throw new IllegalArgumentException("Cannot read filename 'null'!");
        }
        File file = new File(fileName);

        if (!file.exists()) {
            throw new RuntimeException(String.format("Unable to find file '%s'", fileName));
        }
        if (!file.canRead()) {
            throw new RuntimeException(String.format("Unable to read file '%s'", fileName));
        }
        return new StringFileReader().readFileContents(file);
    }

    private static void generateByteCodeFile(String sourceCode, String fileName) {
        try (FileOutputStream fos = new FileOutputStream(fileName + ".class")) {
            ByteCodeGenerator generator = new ByteCodeGenerator();
            byte[] byteCode = generator.generate(sourceCode);
            fos.write(byteCode);
            fos.flush();
        } catch (Exception e) {
            throw new RuntimeException("Failed to write generated bytecode", e);
        }
    }
}
